// Email domain for dedicated newsletter addresses
// MUST be configured via EMAIL_DOMAIN environment variable in production
const EMAIL_DOMAIN = process.env.EMAIL_DOMAIN || "newsletters.example.com"

// Log warning if using default domain (helps catch misconfiguration)
if (!process.env.EMAIL_DOMAIN) {
  console.warn(
    "[emailGeneration] EMAIL_DOMAIN environment variable not set. Using default: newsletters.example.com. " +
      "This MUST be configured for production use."
  )
}

/**
 * Slugifies a name into an email-safe prefix.
 * Strips diacritics, lowercases, replaces non-alphanumeric with hyphens.
 */
export function slugifyName(name: string): string {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip diacritics
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-") // replace non-alphanumeric with hyphens
    .replace(/^-+|-+$/g, "") // trim leading/trailing hyphens
    .slice(0, 30)
    .replace(/-+$/, "") // re-trim if slice cut mid-hyphen
}

/**
 * Generates a unique dedicated email address for a user.
 * Prefers a name-based slug (e.g. teo-goulois-1232@domain),
 * falls back to email username, then to user ID.
 */
export function generateDedicatedEmail(userId: string, name?: string, email?: string): string {
  // Try name-based slug first
  if (name) {
    const slug = slugifyName(name)
    if (slug.length >= 2) {
      const suffix = Math.floor(1000 + Math.random() * 9000)
      return `${slug}-${suffix}@${EMAIL_DOMAIN}`
    }
  }

  // Fallback to email username
  if (email) {
    const localPart = email.split("@")[0] ?? ""
    const slug = slugifyName(localPart)
    if (slug.length >= 2) {
      const suffix = Math.floor(1000 + Math.random() * 9000)
      return `${slug}-${suffix}@${EMAIL_DOMAIN}`
    }
  }

  // Final fallback: last 8 chars of user ID (legacy behavior)
  const idString = userId.toString()
  const prefix = idString.slice(-8).toLowerCase()
  return `${prefix}@${EMAIL_DOMAIN}`
}

/**
 * Validates a custom email prefix chosen by the user during onboarding.
 * Rules: 3-20 chars, lowercase alphanumeric + hyphens, must start/end with letter or number.
 */
export function isValidCustomPrefix(prefix: string): boolean {
  if (!prefix) return false
  if (prefix.length < 3 || prefix.length > 20) return false
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(prefix)
}

/**
 * Builds a full dedicated email from a prefix.
 */
export function buildDedicatedEmail(prefix: string): string {
  return `${prefix}@${EMAIL_DOMAIN}`
}

/**
 * Validates that an email address matches the expected dedicated email format.
 * Accepts both auto-generated 8-char prefixes and custom user-chosen prefixes.
 *
 * @param email - The email address to validate
 * @returns true if the email is a valid dedicated email format
 */
export function isValidDedicatedEmail(email: string): boolean {
  if (!email) return false
  const parts = email.split("@")
  if (parts.length !== 2) return false
  const [prefix, domain] = parts
  if (domain !== EMAIL_DOMAIN) return false
  // Accept auto-generated 8-char format
  const isAutoGenerated = prefix.length === 8 && /^[a-z0-9]+$/.test(prefix)
  // Accept name-based format: slug-4digits (e.g. teo-goulois-1232)
  const isNameBased = /^[a-z0-9][a-z0-9-]*-\d{4}$/.test(prefix) && prefix.length >= 6
  // Accept custom prefix format (3-20 chars)
  return isAutoGenerated || isNameBased || isValidCustomPrefix(prefix)
}

/**
 * Gets the configured email domain
 * Useful for display purposes
 */
export function getEmailDomain(): string {
  return EMAIL_DOMAIN
}
