/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SignupRouteImport } from './routes/{-$locale}/signup'
import { Route as Char123LocaleChar125ResetPasswordRouteImport } from './routes/{-$locale}/reset-password'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125ForgotPasswordRouteImport } from './routes/{-$locale}/forgot-password'
import { Route as Char123LocaleChar1258RouteImport } from './routes/{-$locale}/8'
import { Route as Char123LocaleChar1257RouteImport } from './routes/{-$locale}/7'
import { Route as Char123LocaleChar1256RouteImport } from './routes/{-$locale}/6'
import { Route as Char123LocaleChar1255RouteImport } from './routes/{-$locale}/5'
import { Route as Char123LocaleChar1253RouteImport } from './routes/{-$locale}/3'
import { Route as Char123LocaleChar1251RouteImport } from './routes/{-$locale}/1'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as ShareEmailTokenRouteImport } from './routes/share-email/$token'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedNavigationRouteRouteImport } from './routes/_authed/_navigation/route'
import { Route as AuthedNewslettersIndexRouteImport } from './routes/_authed/newsletters/index'
import { Route as Char123LocaleChar125ShareTokenRouteImport } from './routes/{-$locale}/share/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedNewslettersIdRouteImport } from './routes/_authed/newsletters/$id'
import { Route as AuthedNavigationAdminRouteRouteImport } from './routes/_authed/_navigation/admin/route'
import { Route as AuthedNavigationSettingsIndexRouteImport } from './routes/_authed/_navigation/settings/index'
import { Route as AuthedNavigationImportIndexRouteImport } from './routes/_authed/_navigation/import/index'
import { Route as AuthedNavigationCommunityIndexRouteImport } from './routes/_authed/_navigation/community/index'
import { Route as AuthedNavigationAdminIndexRouteImport } from './routes/_authed/_navigation/admin/index'
import { Route as AuthedNavigationSettingsPrivacyRouteImport } from './routes/_authed/_navigation/settings/privacy'
import { Route as AuthedNavigationImportManualRouteImport } from './routes/_authed/_navigation/import/manual'
import { Route as AuthedNavigationImportCallbackRouteImport } from './routes/_authed/_navigation/import/callback'
import { Route as AuthedNavigationCommunityContentIdRouteImport } from './routes/_authed/_navigation/community/$contentId'
import { Route as AuthedNavigationAdminPrivacyRouteImport } from './routes/_authed/_navigation/admin/privacy'
import { Route as AuthedNavigationAdminModerationRouteImport } from './routes/_authed/_navigation/admin/moderation'
import { Route as AuthedNavigationAdminHealthRouteImport } from './routes/_authed/_navigation/admin/health'
import { Route as AuthedNavigationAdminDeliveryRouteImport } from './routes/_authed/_navigation/admin/delivery'
import { Route as AuthedNavigationAdminCommunityRouteImport } from './routes/_authed/_navigation/admin/community'
import { Route as AuthedNavigationAdminAnalyticsRouteImport } from './routes/_authed/_navigation/admin/analytics'
import { Route as AuthedNavigationCommunitySenderSenderEmailRouteImport } from './routes/_authed/_navigation/community/sender/$senderEmail'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SignupRoute =
  Char123LocaleChar125SignupRouteImport.update({
    id: '/{-$locale}/signup',
    path: '/{-$locale}/signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ResetPasswordRoute =
  Char123LocaleChar125ResetPasswordRouteImport.update({
    id: '/{-$locale}/reset-password',
    path: '/{-$locale}/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/{-$locale}/login',
    path: '/{-$locale}/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ForgotPasswordRoute =
  Char123LocaleChar125ForgotPasswordRouteImport.update({
    id: '/{-$locale}/forgot-password',
    path: '/{-$locale}/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar1258Route = Char123LocaleChar1258RouteImport.update({
  id: '/{-$locale}/8',
  path: '/{-$locale}/8',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar1257Route = Char123LocaleChar1257RouteImport.update({
  id: '/{-$locale}/7',
  path: '/{-$locale}/7',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar1256Route = Char123LocaleChar1256RouteImport.update({
  id: '/{-$locale}/6',
  path: '/{-$locale}/6',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar1255Route = Char123LocaleChar1255RouteImport.update({
  id: '/{-$locale}/5',
  path: '/{-$locale}/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar1253Route = Char123LocaleChar1253RouteImport.update({
  id: '/{-$locale}/3',
  path: '/{-$locale}/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar1251Route = Char123LocaleChar1251RouteImport.update({
  id: '/{-$locale}/1',
  path: '/{-$locale}/1',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareEmailTokenRoute = ShareEmailTokenRouteImport.update({
  id: '/share-email/$token',
  path: '/share-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNavigationRouteRoute = AuthedNavigationRouteRouteImport.update({
  id: '/_navigation',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewslettersIndexRoute = AuthedNewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => AuthedRoute,
} as any)
const Char123LocaleChar125ShareTokenRoute =
  Char123LocaleChar125ShareTokenRouteImport.update({
    id: '/{-$locale}/share/$token',
    path: '/{-$locale}/share/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNewslettersIdRoute = AuthedNewslettersIdRouteImport.update({
  id: '/newsletters/$id',
  path: '/newsletters/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNavigationAdminRouteRoute =
  AuthedNavigationAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationSettingsIndexRoute =
  AuthedNavigationSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationImportIndexRoute =
  AuthedNavigationImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationCommunityIndexRoute =
  AuthedNavigationCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationAdminIndexRoute =
  AuthedNavigationAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedNavigationAdminRouteRoute,
  } as any)
const AuthedNavigationSettingsPrivacyRoute =
  AuthedNavigationSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationImportManualRoute =
  AuthedNavigationImportManualRouteImport.update({
    id: '/import/manual',
    path: '/import/manual',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationImportCallbackRoute =
  AuthedNavigationImportCallbackRouteImport.update({
    id: '/import/callback',
    path: '/import/callback',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationCommunityContentIdRoute =
  AuthedNavigationCommunityContentIdRouteImport.update({
    id: '/community/$contentId',
    path: '/community/$contentId',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)
const AuthedNavigationAdminPrivacyRoute =
  AuthedNavigationAdminPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthedNavigationAdminRouteRoute,
  } as any)
const AuthedNavigationAdminModerationRoute =
  AuthedNavigationAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthedNavigationAdminRouteRoute,
  } as any)
const AuthedNavigationAdminHealthRoute =
  AuthedNavigationAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthedNavigationAdminRouteRoute,
  } as any)
const AuthedNavigationAdminDeliveryRoute =
  AuthedNavigationAdminDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthedNavigationAdminRouteRoute,
  } as any)
const AuthedNavigationAdminCommunityRoute =
  AuthedNavigationAdminCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthedNavigationAdminRouteRoute,
  } as any)
const AuthedNavigationAdminAnalyticsRoute =
  AuthedNavigationAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthedNavigationAdminRouteRoute,
  } as any)
const AuthedNavigationCommunitySenderSenderEmailRoute =
  AuthedNavigationCommunitySenderSenderEmailRouteImport.update({
    id: '/community/sender/$senderEmail',
    path: '/community/sender/$senderEmail',
    getParentRoute: () => AuthedNavigationRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedNavigationRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/share-email/$token': typeof ShareEmailTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/{-$locale}/1': typeof Char123LocaleChar1251Route
  '/{-$locale}/3': typeof Char123LocaleChar1253Route
  '/{-$locale}/5': typeof Char123LocaleChar1255Route
  '/{-$locale}/6': typeof Char123LocaleChar1256Route
  '/{-$locale}/7': typeof Char123LocaleChar1257Route
  '/{-$locale}/8': typeof Char123LocaleChar1258Route
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125SignupRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/admin': typeof AuthedNavigationAdminRouteRouteWithChildren
  '/newsletters/$id': typeof AuthedNewslettersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/share/$token': typeof Char123LocaleChar125ShareTokenRoute
  '/newsletters/': typeof AuthedNewslettersIndexRoute
  '/admin/analytics': typeof AuthedNavigationAdminAnalyticsRoute
  '/admin/community': typeof AuthedNavigationAdminCommunityRoute
  '/admin/delivery': typeof AuthedNavigationAdminDeliveryRoute
  '/admin/health': typeof AuthedNavigationAdminHealthRoute
  '/admin/moderation': typeof AuthedNavigationAdminModerationRoute
  '/admin/privacy': typeof AuthedNavigationAdminPrivacyRoute
  '/community/$contentId': typeof AuthedNavigationCommunityContentIdRoute
  '/import/callback': typeof AuthedNavigationImportCallbackRoute
  '/import/manual': typeof AuthedNavigationImportManualRoute
  '/settings/privacy': typeof AuthedNavigationSettingsPrivacyRoute
  '/admin/': typeof AuthedNavigationAdminIndexRoute
  '/community/': typeof AuthedNavigationCommunityIndexRoute
  '/import/': typeof AuthedNavigationImportIndexRoute
  '/settings/': typeof AuthedNavigationSettingsIndexRoute
  '/community/sender/$senderEmail': typeof AuthedNavigationCommunitySenderSenderEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedNavigationRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/share-email/$token': typeof ShareEmailTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/{-$locale}/1': typeof Char123LocaleChar1251Route
  '/{-$locale}/3': typeof Char123LocaleChar1253Route
  '/{-$locale}/5': typeof Char123LocaleChar1255Route
  '/{-$locale}/6': typeof Char123LocaleChar1256Route
  '/{-$locale}/7': typeof Char123LocaleChar1257Route
  '/{-$locale}/8': typeof Char123LocaleChar1258Route
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125SignupRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/newsletters/$id': typeof AuthedNewslettersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/share/$token': typeof Char123LocaleChar125ShareTokenRoute
  '/newsletters': typeof AuthedNewslettersIndexRoute
  '/admin/analytics': typeof AuthedNavigationAdminAnalyticsRoute
  '/admin/community': typeof AuthedNavigationAdminCommunityRoute
  '/admin/delivery': typeof AuthedNavigationAdminDeliveryRoute
  '/admin/health': typeof AuthedNavigationAdminHealthRoute
  '/admin/moderation': typeof AuthedNavigationAdminModerationRoute
  '/admin/privacy': typeof AuthedNavigationAdminPrivacyRoute
  '/community/$contentId': typeof AuthedNavigationCommunityContentIdRoute
  '/import/callback': typeof AuthedNavigationImportCallbackRoute
  '/import/manual': typeof AuthedNavigationImportManualRoute
  '/settings/privacy': typeof AuthedNavigationSettingsPrivacyRoute
  '/admin': typeof AuthedNavigationAdminIndexRoute
  '/community': typeof AuthedNavigationCommunityIndexRoute
  '/import': typeof AuthedNavigationImportIndexRoute
  '/settings': typeof AuthedNavigationSettingsIndexRoute
  '/community/sender/$senderEmail': typeof AuthedNavigationCommunitySenderSenderEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_navigation': typeof AuthedNavigationRouteRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/share-email/$token': typeof ShareEmailTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/{-$locale}/1': typeof Char123LocaleChar1251Route
  '/{-$locale}/3': typeof Char123LocaleChar1253Route
  '/{-$locale}/5': typeof Char123LocaleChar1255Route
  '/{-$locale}/6': typeof Char123LocaleChar1256Route
  '/{-$locale}/7': typeof Char123LocaleChar1257Route
  '/{-$locale}/8': typeof Char123LocaleChar1258Route
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125SignupRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/_authed/_navigation/admin': typeof AuthedNavigationAdminRouteRouteWithChildren
  '/_authed/newsletters/$id': typeof AuthedNewslettersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/{-$locale}/share/$token': typeof Char123LocaleChar125ShareTokenRoute
  '/_authed/newsletters/': typeof AuthedNewslettersIndexRoute
  '/_authed/_navigation/admin/analytics': typeof AuthedNavigationAdminAnalyticsRoute
  '/_authed/_navigation/admin/community': typeof AuthedNavigationAdminCommunityRoute
  '/_authed/_navigation/admin/delivery': typeof AuthedNavigationAdminDeliveryRoute
  '/_authed/_navigation/admin/health': typeof AuthedNavigationAdminHealthRoute
  '/_authed/_navigation/admin/moderation': typeof AuthedNavigationAdminModerationRoute
  '/_authed/_navigation/admin/privacy': typeof AuthedNavigationAdminPrivacyRoute
  '/_authed/_navigation/community/$contentId': typeof AuthedNavigationCommunityContentIdRoute
  '/_authed/_navigation/import/callback': typeof AuthedNavigationImportCallbackRoute
  '/_authed/_navigation/import/manual': typeof AuthedNavigationImportManualRoute
  '/_authed/_navigation/settings/privacy': typeof AuthedNavigationSettingsPrivacyRoute
  '/_authed/_navigation/admin/': typeof AuthedNavigationAdminIndexRoute
  '/_authed/_navigation/community/': typeof AuthedNavigationCommunityIndexRoute
  '/_authed/_navigation/import/': typeof AuthedNavigationImportIndexRoute
  '/_authed/_navigation/settings/': typeof AuthedNavigationSettingsIndexRoute
  '/_authed/_navigation/community/sender/$senderEmail': typeof AuthedNavigationCommunitySenderSenderEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/share-email/$token'
    | '/share/$token'
    | '/{-$locale}/1'
    | '/{-$locale}/3'
    | '/{-$locale}/5'
    | '/{-$locale}/6'
    | '/{-$locale}/7'
    | '/{-$locale}/8'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/signup'
    | '/{-$locale}/'
    | '/admin'
    | '/newsletters/$id'
    | '/api/auth/$'
    | '/{-$locale}/share/$token'
    | '/newsletters/'
    | '/admin/analytics'
    | '/admin/community'
    | '/admin/delivery'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/privacy'
    | '/community/$contentId'
    | '/import/callback'
    | '/import/manual'
    | '/settings/privacy'
    | '/admin/'
    | '/community/'
    | '/import/'
    | '/settings/'
    | '/community/sender/$senderEmail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/share-email/$token'
    | '/share/$token'
    | '/{-$locale}/1'
    | '/{-$locale}/3'
    | '/{-$locale}/5'
    | '/{-$locale}/6'
    | '/{-$locale}/7'
    | '/{-$locale}/8'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/signup'
    | '/{-$locale}'
    | '/newsletters/$id'
    | '/api/auth/$'
    | '/{-$locale}/share/$token'
    | '/newsletters'
    | '/admin/analytics'
    | '/admin/community'
    | '/admin/delivery'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/privacy'
    | '/community/$contentId'
    | '/import/callback'
    | '/import/manual'
    | '/settings/privacy'
    | '/admin'
    | '/community'
    | '/import'
    | '/settings'
    | '/community/sender/$senderEmail'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/_navigation'
    | '/_authed/onboarding'
    | '/share-email/$token'
    | '/share/$token'
    | '/{-$locale}/1'
    | '/{-$locale}/3'
    | '/{-$locale}/5'
    | '/{-$locale}/6'
    | '/{-$locale}/7'
    | '/{-$locale}/8'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/signup'
    | '/{-$locale}/'
    | '/_authed/_navigation/admin'
    | '/_authed/newsletters/$id'
    | '/api/auth/$'
    | '/{-$locale}/share/$token'
    | '/_authed/newsletters/'
    | '/_authed/_navigation/admin/analytics'
    | '/_authed/_navigation/admin/community'
    | '/_authed/_navigation/admin/delivery'
    | '/_authed/_navigation/admin/health'
    | '/_authed/_navigation/admin/moderation'
    | '/_authed/_navigation/admin/privacy'
    | '/_authed/_navigation/community/$contentId'
    | '/_authed/_navigation/import/callback'
    | '/_authed/_navigation/import/manual'
    | '/_authed/_navigation/settings/privacy'
    | '/_authed/_navigation/admin/'
    | '/_authed/_navigation/community/'
    | '/_authed/_navigation/import/'
    | '/_authed/_navigation/settings/'
    | '/_authed/_navigation/community/sender/$senderEmail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ShareEmailTokenRoute: typeof ShareEmailTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  Char123LocaleChar1251Route: typeof Char123LocaleChar1251Route
  Char123LocaleChar1253Route: typeof Char123LocaleChar1253Route
  Char123LocaleChar1255Route: typeof Char123LocaleChar1255Route
  Char123LocaleChar1256Route: typeof Char123LocaleChar1256Route
  Char123LocaleChar1257Route: typeof Char123LocaleChar1257Route
  Char123LocaleChar1258Route: typeof Char123LocaleChar1258Route
  Char123LocaleChar125ForgotPasswordRoute: typeof Char123LocaleChar125ForgotPasswordRoute
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125ResetPasswordRoute: typeof Char123LocaleChar125ResetPasswordRoute
  Char123LocaleChar125SignupRoute: typeof Char123LocaleChar125SignupRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  Char123LocaleChar125ShareTokenRoute: typeof Char123LocaleChar125ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/signup': {
      id: '/{-$locale}/signup'
      path: '/{-$locale}/signup'
      fullPath: '/{-$locale}/signup'
      preLoaderRoute: typeof Char123LocaleChar125SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/reset-password': {
      id: '/{-$locale}/reset-password'
      path: '/{-$locale}/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/{-$locale}/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/forgot-password': {
      id: '/{-$locale}/forgot-password'
      path: '/{-$locale}/forgot-password'
      fullPath: '/{-$locale}/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/8': {
      id: '/{-$locale}/8'
      path: '/{-$locale}/8'
      fullPath: '/{-$locale}/8'
      preLoaderRoute: typeof Char123LocaleChar1258RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/7': {
      id: '/{-$locale}/7'
      path: '/{-$locale}/7'
      fullPath: '/{-$locale}/7'
      preLoaderRoute: typeof Char123LocaleChar1257RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/6': {
      id: '/{-$locale}/6'
      path: '/{-$locale}/6'
      fullPath: '/{-$locale}/6'
      preLoaderRoute: typeof Char123LocaleChar1256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/5': {
      id: '/{-$locale}/5'
      path: '/{-$locale}/5'
      fullPath: '/{-$locale}/5'
      preLoaderRoute: typeof Char123LocaleChar1255RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/3': {
      id: '/{-$locale}/3'
      path: '/{-$locale}/3'
      fullPath: '/{-$locale}/3'
      preLoaderRoute: typeof Char123LocaleChar1253RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/1': {
      id: '/{-$locale}/1'
      path: '/{-$locale}/1'
      fullPath: '/{-$locale}/1'
      preLoaderRoute: typeof Char123LocaleChar1251RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-email/$token': {
      id: '/share-email/$token'
      path: '/share-email/$token'
      fullPath: '/share-email/$token'
      preLoaderRoute: typeof ShareEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_navigation': {
      id: '/_authed/_navigation'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedNavigationRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/newsletters/': {
      id: '/_authed/newsletters/'
      path: '/newsletters'
      fullPath: '/newsletters/'
      preLoaderRoute: typeof AuthedNewslettersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/{-$locale}/share/$token': {
      id: '/{-$locale}/share/$token'
      path: '/{-$locale}/share/$token'
      fullPath: '/{-$locale}/share/$token'
      preLoaderRoute: typeof Char123LocaleChar125ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/newsletters/$id': {
      id: '/_authed/newsletters/$id'
      path: '/newsletters/$id'
      fullPath: '/newsletters/$id'
      preLoaderRoute: typeof AuthedNewslettersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_navigation/admin': {
      id: '/_authed/_navigation/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedNavigationAdminRouteRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/settings/': {
      id: '/_authed/_navigation/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedNavigationSettingsIndexRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/import/': {
      id: '/_authed/_navigation/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthedNavigationImportIndexRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/community/': {
      id: '/_authed/_navigation/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthedNavigationCommunityIndexRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/admin/': {
      id: '/_authed/_navigation/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedNavigationAdminIndexRouteImport
      parentRoute: typeof AuthedNavigationAdminRouteRoute
    }
    '/_authed/_navigation/settings/privacy': {
      id: '/_authed/_navigation/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthedNavigationSettingsPrivacyRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/import/manual': {
      id: '/_authed/_navigation/import/manual'
      path: '/import/manual'
      fullPath: '/import/manual'
      preLoaderRoute: typeof AuthedNavigationImportManualRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/import/callback': {
      id: '/_authed/_navigation/import/callback'
      path: '/import/callback'
      fullPath: '/import/callback'
      preLoaderRoute: typeof AuthedNavigationImportCallbackRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/community/$contentId': {
      id: '/_authed/_navigation/community/$contentId'
      path: '/community/$contentId'
      fullPath: '/community/$contentId'
      preLoaderRoute: typeof AuthedNavigationCommunityContentIdRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
    '/_authed/_navigation/admin/privacy': {
      id: '/_authed/_navigation/admin/privacy'
      path: '/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AuthedNavigationAdminPrivacyRouteImport
      parentRoute: typeof AuthedNavigationAdminRouteRoute
    }
    '/_authed/_navigation/admin/moderation': {
      id: '/_authed/_navigation/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthedNavigationAdminModerationRouteImport
      parentRoute: typeof AuthedNavigationAdminRouteRoute
    }
    '/_authed/_navigation/admin/health': {
      id: '/_authed/_navigation/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthedNavigationAdminHealthRouteImport
      parentRoute: typeof AuthedNavigationAdminRouteRoute
    }
    '/_authed/_navigation/admin/delivery': {
      id: '/_authed/_navigation/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthedNavigationAdminDeliveryRouteImport
      parentRoute: typeof AuthedNavigationAdminRouteRoute
    }
    '/_authed/_navigation/admin/community': {
      id: '/_authed/_navigation/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthedNavigationAdminCommunityRouteImport
      parentRoute: typeof AuthedNavigationAdminRouteRoute
    }
    '/_authed/_navigation/admin/analytics': {
      id: '/_authed/_navigation/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthedNavigationAdminAnalyticsRouteImport
      parentRoute: typeof AuthedNavigationAdminRouteRoute
    }
    '/_authed/_navigation/community/sender/$senderEmail': {
      id: '/_authed/_navigation/community/sender/$senderEmail'
      path: '/community/sender/$senderEmail'
      fullPath: '/community/sender/$senderEmail'
      preLoaderRoute: typeof AuthedNavigationCommunitySenderSenderEmailRouteImport
      parentRoute: typeof AuthedNavigationRouteRoute
    }
  }
}

interface AuthedNavigationAdminRouteRouteChildren {
  AuthedNavigationAdminAnalyticsRoute: typeof AuthedNavigationAdminAnalyticsRoute
  AuthedNavigationAdminCommunityRoute: typeof AuthedNavigationAdminCommunityRoute
  AuthedNavigationAdminDeliveryRoute: typeof AuthedNavigationAdminDeliveryRoute
  AuthedNavigationAdminHealthRoute: typeof AuthedNavigationAdminHealthRoute
  AuthedNavigationAdminModerationRoute: typeof AuthedNavigationAdminModerationRoute
  AuthedNavigationAdminPrivacyRoute: typeof AuthedNavigationAdminPrivacyRoute
  AuthedNavigationAdminIndexRoute: typeof AuthedNavigationAdminIndexRoute
}

const AuthedNavigationAdminRouteRouteChildren: AuthedNavigationAdminRouteRouteChildren =
  {
    AuthedNavigationAdminAnalyticsRoute: AuthedNavigationAdminAnalyticsRoute,
    AuthedNavigationAdminCommunityRoute: AuthedNavigationAdminCommunityRoute,
    AuthedNavigationAdminDeliveryRoute: AuthedNavigationAdminDeliveryRoute,
    AuthedNavigationAdminHealthRoute: AuthedNavigationAdminHealthRoute,
    AuthedNavigationAdminModerationRoute: AuthedNavigationAdminModerationRoute,
    AuthedNavigationAdminPrivacyRoute: AuthedNavigationAdminPrivacyRoute,
    AuthedNavigationAdminIndexRoute: AuthedNavigationAdminIndexRoute,
  }

const AuthedNavigationAdminRouteRouteWithChildren =
  AuthedNavigationAdminRouteRoute._addFileChildren(
    AuthedNavigationAdminRouteRouteChildren,
  )

interface AuthedNavigationRouteRouteChildren {
  AuthedNavigationAdminRouteRoute: typeof AuthedNavigationAdminRouteRouteWithChildren
  AuthedNavigationCommunityContentIdRoute: typeof AuthedNavigationCommunityContentIdRoute
  AuthedNavigationImportCallbackRoute: typeof AuthedNavigationImportCallbackRoute
  AuthedNavigationImportManualRoute: typeof AuthedNavigationImportManualRoute
  AuthedNavigationSettingsPrivacyRoute: typeof AuthedNavigationSettingsPrivacyRoute
  AuthedNavigationCommunityIndexRoute: typeof AuthedNavigationCommunityIndexRoute
  AuthedNavigationImportIndexRoute: typeof AuthedNavigationImportIndexRoute
  AuthedNavigationSettingsIndexRoute: typeof AuthedNavigationSettingsIndexRoute
  AuthedNavigationCommunitySenderSenderEmailRoute: typeof AuthedNavigationCommunitySenderSenderEmailRoute
}

const AuthedNavigationRouteRouteChildren: AuthedNavigationRouteRouteChildren = {
  AuthedNavigationAdminRouteRoute: AuthedNavigationAdminRouteRouteWithChildren,
  AuthedNavigationCommunityContentIdRoute:
    AuthedNavigationCommunityContentIdRoute,
  AuthedNavigationImportCallbackRoute: AuthedNavigationImportCallbackRoute,
  AuthedNavigationImportManualRoute: AuthedNavigationImportManualRoute,
  AuthedNavigationSettingsPrivacyRoute: AuthedNavigationSettingsPrivacyRoute,
  AuthedNavigationCommunityIndexRoute: AuthedNavigationCommunityIndexRoute,
  AuthedNavigationImportIndexRoute: AuthedNavigationImportIndexRoute,
  AuthedNavigationSettingsIndexRoute: AuthedNavigationSettingsIndexRoute,
  AuthedNavigationCommunitySenderSenderEmailRoute:
    AuthedNavigationCommunitySenderSenderEmailRoute,
}

const AuthedNavigationRouteRouteWithChildren =
  AuthedNavigationRouteRoute._addFileChildren(
    AuthedNavigationRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedNavigationRouteRoute: typeof AuthedNavigationRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedNewslettersIdRoute: typeof AuthedNewslettersIdRoute
  AuthedNewslettersIndexRoute: typeof AuthedNewslettersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedNavigationRouteRoute: AuthedNavigationRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedNewslettersIdRoute: AuthedNewslettersIdRoute,
  AuthedNewslettersIndexRoute: AuthedNewslettersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ShareEmailTokenRoute: ShareEmailTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  Char123LocaleChar1251Route: Char123LocaleChar1251Route,
  Char123LocaleChar1253Route: Char123LocaleChar1253Route,
  Char123LocaleChar1255Route: Char123LocaleChar1255Route,
  Char123LocaleChar1256Route: Char123LocaleChar1256Route,
  Char123LocaleChar1257Route: Char123LocaleChar1257Route,
  Char123LocaleChar1258Route: Char123LocaleChar1258Route,
  Char123LocaleChar125ForgotPasswordRoute:
    Char123LocaleChar125ForgotPasswordRoute,
  Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
  Char123LocaleChar125ResetPasswordRoute:
    Char123LocaleChar125ResetPasswordRoute,
  Char123LocaleChar125SignupRoute: Char123LocaleChar125SignupRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  Char123LocaleChar125ShareTokenRoute: Char123LocaleChar125ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
