/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedNewslettersIndexRouteImport } from './routes/_authed/newsletters/index'
import { Route as AuthedImportIndexRouteImport } from './routes/_authed/import/index'
import { Route as AuthedCommunityIndexRouteImport } from './routes/_authed/community/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsPrivacyRouteImport } from './routes/_authed/settings/privacy'
import { Route as AuthedNewslettersIdRouteImport } from './routes/_authed/newsletters/$id'
import { Route as AuthedCommunityContentIdRouteImport } from './routes/_authed/community/$contentId'
import { Route as AuthedAdminPrivacyRouteImport } from './routes/_authed/admin/privacy'
import { Route as AuthedAdminHealthRouteImport } from './routes/_authed/admin/health'
import { Route as AuthedAdminDeliveryRouteImport } from './routes/_authed/admin/delivery'
import { Route as AuthedAdminCommunityRouteImport } from './routes/_authed/admin/community'
import { Route as AuthedCommunitySenderSenderEmailRouteImport } from './routes/_authed/community/sender/$senderEmail'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewslettersIndexRoute = AuthedNewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImportIndexRoute = AuthedImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommunityIndexRoute = AuthedCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsPrivacyRoute = AuthedSettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewslettersIdRoute = AuthedNewslettersIdRouteImport.update({
  id: '/newsletters/$id',
  path: '/newsletters/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommunityContentIdRoute =
  AuthedCommunityContentIdRouteImport.update({
    id: '/community/$contentId',
    path: '/community/$contentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminPrivacyRoute = AuthedAdminPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminHealthRoute = AuthedAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminDeliveryRoute = AuthedAdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCommunityRoute = AuthedAdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedCommunitySenderSenderEmailRoute =
  AuthedCommunitySenderSenderEmailRouteImport.update({
    id: '/community/sender/$senderEmail',
    path: '/community/sender/$senderEmail',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/admin/community': typeof AuthedAdminCommunityRoute
  '/admin/delivery': typeof AuthedAdminDeliveryRoute
  '/admin/health': typeof AuthedAdminHealthRoute
  '/admin/privacy': typeof AuthedAdminPrivacyRoute
  '/community/$contentId': typeof AuthedCommunityContentIdRoute
  '/newsletters/$id': typeof AuthedNewslettersIdRoute
  '/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/community/': typeof AuthedCommunityIndexRoute
  '/import/': typeof AuthedImportIndexRoute
  '/newsletters/': typeof AuthedNewslettersIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/community/sender/$senderEmail': typeof AuthedCommunitySenderSenderEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/community': typeof AuthedAdminCommunityRoute
  '/admin/delivery': typeof AuthedAdminDeliveryRoute
  '/admin/health': typeof AuthedAdminHealthRoute
  '/admin/privacy': typeof AuthedAdminPrivacyRoute
  '/community/$contentId': typeof AuthedCommunityContentIdRoute
  '/newsletters/$id': typeof AuthedNewslettersIdRoute
  '/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/community': typeof AuthedCommunityIndexRoute
  '/import': typeof AuthedImportIndexRoute
  '/newsletters': typeof AuthedNewslettersIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/community/sender/$senderEmail': typeof AuthedCommunitySenderSenderEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/admin/community': typeof AuthedAdminCommunityRoute
  '/_authed/admin/delivery': typeof AuthedAdminDeliveryRoute
  '/_authed/admin/health': typeof AuthedAdminHealthRoute
  '/_authed/admin/privacy': typeof AuthedAdminPrivacyRoute
  '/_authed/community/$contentId': typeof AuthedCommunityContentIdRoute
  '/_authed/newsletters/$id': typeof AuthedNewslettersIdRoute
  '/_authed/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/community/': typeof AuthedCommunityIndexRoute
  '/_authed/import/': typeof AuthedImportIndexRoute
  '/_authed/newsletters/': typeof AuthedNewslettersIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/community/sender/$senderEmail': typeof AuthedCommunitySenderSenderEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/admin/community'
    | '/admin/delivery'
    | '/admin/health'
    | '/admin/privacy'
    | '/community/$contentId'
    | '/newsletters/$id'
    | '/settings/privacy'
    | '/api/auth/$'
    | '/admin/'
    | '/community/'
    | '/import/'
    | '/newsletters/'
    | '/settings/'
    | '/community/sender/$senderEmail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/community'
    | '/admin/delivery'
    | '/admin/health'
    | '/admin/privacy'
    | '/community/$contentId'
    | '/newsletters/$id'
    | '/settings/privacy'
    | '/api/auth/$'
    | '/admin'
    | '/community'
    | '/import'
    | '/newsletters'
    | '/settings'
    | '/community/sender/$senderEmail'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/admin/community'
    | '/_authed/admin/delivery'
    | '/_authed/admin/health'
    | '/_authed/admin/privacy'
    | '/_authed/community/$contentId'
    | '/_authed/newsletters/$id'
    | '/_authed/settings/privacy'
    | '/api/auth/$'
    | '/_authed/admin/'
    | '/_authed/community/'
    | '/_authed/import/'
    | '/_authed/newsletters/'
    | '/_authed/settings/'
    | '/_authed/community/sender/$senderEmail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/newsletters/': {
      id: '/_authed/newsletters/'
      path: '/newsletters'
      fullPath: '/newsletters/'
      preLoaderRoute: typeof AuthedNewslettersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/import/': {
      id: '/_authed/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthedImportIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/community/': {
      id: '/_authed/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthedCommunityIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/privacy': {
      id: '/_authed/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthedSettingsPrivacyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/newsletters/$id': {
      id: '/_authed/newsletters/$id'
      path: '/newsletters/$id'
      fullPath: '/newsletters/$id'
      preLoaderRoute: typeof AuthedNewslettersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/community/$contentId': {
      id: '/_authed/community/$contentId'
      path: '/community/$contentId'
      fullPath: '/community/$contentId'
      preLoaderRoute: typeof AuthedCommunityContentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/privacy': {
      id: '/_authed/admin/privacy'
      path: '/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AuthedAdminPrivacyRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/health': {
      id: '/_authed/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthedAdminHealthRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/delivery': {
      id: '/_authed/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AuthedAdminDeliveryRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/community': {
      id: '/_authed/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthedAdminCommunityRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/community/sender/$senderEmail': {
      id: '/_authed/community/sender/$senderEmail'
      path: '/community/sender/$senderEmail'
      fullPath: '/community/sender/$senderEmail'
      preLoaderRoute: typeof AuthedCommunitySenderSenderEmailRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminCommunityRoute: typeof AuthedAdminCommunityRoute
  AuthedAdminDeliveryRoute: typeof AuthedAdminDeliveryRoute
  AuthedAdminHealthRoute: typeof AuthedAdminHealthRoute
  AuthedAdminPrivacyRoute: typeof AuthedAdminPrivacyRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminCommunityRoute: AuthedAdminCommunityRoute,
  AuthedAdminDeliveryRoute: AuthedAdminDeliveryRoute,
  AuthedAdminHealthRoute: AuthedAdminHealthRoute,
  AuthedAdminPrivacyRoute: AuthedAdminPrivacyRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedCommunityContentIdRoute: typeof AuthedCommunityContentIdRoute
  AuthedNewslettersIdRoute: typeof AuthedNewslettersIdRoute
  AuthedSettingsPrivacyRoute: typeof AuthedSettingsPrivacyRoute
  AuthedCommunityIndexRoute: typeof AuthedCommunityIndexRoute
  AuthedImportIndexRoute: typeof AuthedImportIndexRoute
  AuthedNewslettersIndexRoute: typeof AuthedNewslettersIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedCommunitySenderSenderEmailRoute: typeof AuthedCommunitySenderSenderEmailRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedCommunityContentIdRoute: AuthedCommunityContentIdRoute,
  AuthedNewslettersIdRoute: AuthedNewslettersIdRoute,
  AuthedSettingsPrivacyRoute: AuthedSettingsPrivacyRoute,
  AuthedCommunityIndexRoute: AuthedCommunityIndexRoute,
  AuthedImportIndexRoute: AuthedImportIndexRoute,
  AuthedNewslettersIndexRoute: AuthedNewslettersIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedCommunitySenderSenderEmailRoute: AuthedCommunitySenderSenderEmailRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
